#配置视图解析器
spring:
 datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
 mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

server:
  servlet:
    jsp:
      init-parameters:
        development: true   #用于实现JSP页面热部署
mybatis:
  mapper-locations: classpath:com/mxy/mapper/xml/*.xml
  type-aliases-package: com.mxy.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
