package com.hotel.mapper;

import com.hotel.entity.Customer;
import com.hotel.entity.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    Customer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_customer
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    int updateByPrimaryKey(Customer record);
}