package com.hotel.mapper;

import com.hotel.entity.Room;
import com.hotel.entity.RoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    long countByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insertSelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    List<Room> selectByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    Room selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Room record, @Param("example") RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExample(@Param("record") Room record, @Param("example") RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKeySelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_room
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKey(Room record);
}