package com.hotel.mapper;

import com.hotel.entity.Stuff;
import com.hotel.entity.StuffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    long countByExample(StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByExample(StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByPrimaryKey(Integer stuffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insert(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insertSelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    List<Stuff> selectByExample(StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    Stuff selectByPrimaryKey(Integer stuffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Stuff record, @Param("example") StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExample(@Param("record") Stuff record, @Param("example") StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKeySelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKey(Stuff record);
}