package com.hotel.entity;

public class Reception {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_reception.reception_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer receptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_reception.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer stuffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_reception.reception_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String receptionPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_reception.reception_id
     *
     * @return the value of tab_reception.reception_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getReceptionId() {
        return receptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_reception.reception_id
     *
     * @param receptionId the value for tab_reception.reception_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setReceptionId(Integer receptionId) {
        this.receptionId = receptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_reception.stuff_id
     *
     * @return the value of tab_reception.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStuffId() {
        return stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_reception.stuff_id
     *
     * @param stuffId the value for tab_reception.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffId(Integer stuffId) {
        this.stuffId = stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_reception.reception_password
     *
     * @return the value of tab_reception.reception_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getReceptionPassword() {
        return receptionPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_reception.reception_password
     *
     * @param receptionPassword the value for tab_reception.reception_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setReceptionPassword(String receptionPassword) {
        this.receptionPassword = receptionPassword;
    }
}