package com.hotel.entity;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer staffAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String staffType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer staffTele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String staffCardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String staffAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_staff.staff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Byte staffStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_id
     *
     * @return the value of tab_staff.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_id
     *
     * @param staffId the value for tab_staff.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_name
     *
     * @return the value of tab_staff.staff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_name
     *
     * @param staffName the value for tab_staff.staff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_age
     *
     * @return the value of tab_staff.staff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStaffAge() {
        return staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_age
     *
     * @param staffAge the value for tab_staff.staff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffAge(Integer staffAge) {
        this.staffAge = staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_type
     *
     * @return the value of tab_staff.staff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStaffType() {
        return staffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_type
     *
     * @param staffType the value for tab_staff.staff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffType(String staffType) {
        this.staffType = staffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_tele
     *
     * @return the value of tab_staff.staff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStaffTele() {
        return staffTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_tele
     *
     * @param staffTele the value for tab_staff.staff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffTele(Integer staffTele) {
        this.staffTele = staffTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_cardnumber
     *
     * @return the value of tab_staff.staff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStaffCardnumber() {
        return staffCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_cardnumber
     *
     * @param staffCardnumber the value for tab_staff.staff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffCardnumber(String staffCardnumber) {
        this.staffCardnumber = staffCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_adress
     *
     * @return the value of tab_staff.staff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStaffAdress() {
        return staffAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_adress
     *
     * @param staffAdress the value for tab_staff.staff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffAdress(String staffAdress) {
        this.staffAdress = staffAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_staff.staff_status
     *
     * @return the value of tab_staff.staff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Byte getStaffStatus() {
        return staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_staff.staff_status
     *
     * @param staffStatus the value for tab_staff.staff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffStatus(Byte staffStatus) {
        this.staffStatus = staffStatus;
    }
}