package com.hotel.mapper;

import com.hotel.entity.Reception;
import com.hotel.entity.ReceptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    long countByExample(ReceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByExample(ReceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int deleteByPrimaryKey(Integer receptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insert(Reception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int insertSelective(Reception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    List<Reception> selectByExample(ReceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    Reception selectByPrimaryKey(Integer receptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Reception record, @Param("example") ReceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByExample(@Param("record") Reception record, @Param("example") ReceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKeySelective(Reception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_reception
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    int updateByPrimaryKey(Reception record);
}