package com.hotel.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_admin.admin_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_admin.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_admin.admin_username
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String adminUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_admin.admin_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String adminPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_admin.admin_id
     *
     * @return the value of tab_admin.admin_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_admin.admin_id
     *
     * @param adminId the value for tab_admin.admin_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_admin.staff_id
     *
     * @return the value of tab_admin.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_admin.staff_id
     *
     * @param staffId the value for tab_admin.staff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_admin.admin_username
     *
     * @return the value of tab_admin.admin_username
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getAdminUsername() {
        return adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_admin.admin_username
     *
     * @param adminUsername the value for tab_admin.admin_username
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_admin.admin_password
     *
     * @return the value of tab_admin.admin_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_admin.admin_password
     *
     * @param adminPassword the value for tab_admin.admin_password
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
}