package com.hotel.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_sex
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String customerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_cardnumber
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String customerCardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_age
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Integer customerAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_tele
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String customerTele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_customer.customer_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Byte customerStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_id
     *
     * @return the value of tab_customer.customer_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_id
     *
     * @param customerId the value for tab_customer.customer_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_name
     *
     * @return the value of tab_customer.customer_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_name
     *
     * @param customerName the value for tab_customer.customer_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_sex
     *
     * @return the value of tab_customer.customer_sex
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_sex
     *
     * @param customerSex the value for tab_customer.customer_sex
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_cardnumber
     *
     * @return the value of tab_customer.customer_cardnumber
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getCustomerCardnumber() {
        return customerCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_cardnumber
     *
     * @param customerCardnumber the value for tab_customer.customer_cardnumber
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerCardnumber(String customerCardnumber) {
        this.customerCardnumber = customerCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_age
     *
     * @return the value of tab_customer.customer_age
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Integer getCustomerAge() {
        return customerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_age
     *
     * @param customerAge the value for tab_customer.customer_age
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerAge(Integer customerAge) {
        this.customerAge = customerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_tele
     *
     * @return the value of tab_customer.customer_tele
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getCustomerTele() {
        return customerTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_tele
     *
     * @param customerTele the value for tab_customer.customer_tele
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerTele(String customerTele) {
        this.customerTele = customerTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_customer.customer_status
     *
     * @return the value of tab_customer.customer_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Byte getCustomerStatus() {
        return customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_customer.customer_status
     *
     * @param customerStatus the value for tab_customer.customer_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setCustomerStatus(Byte customerStatus) {
        this.customerStatus = customerStatus;
    }
}