package com.hotel.entity;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_room.room_id
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_room.room_type
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    private String roomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_room.room_number
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_room.room_status
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    private Byte roomStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_room.room_id
     *
     * @return the value of tab_room.room_id
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_room.room_id
     *
     * @param roomId the value for tab_room.room_id
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_room.room_type
     *
     * @return the value of tab_room.room_type
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_room.room_type
     *
     * @param roomType the value for tab_room.room_type
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_room.room_number
     *
     * @return the value of tab_room.room_number
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_room.room_number
     *
     * @param roomNumber the value for tab_room.room_number
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_room.room_status
     *
     * @return the value of tab_room.room_status
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public Byte getRoomStatus() {
        return roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_room.room_status
     *
     * @param roomStatus the value for tab_room.room_status
     *
     * @mbg.generated Fri Jul 10 16:23:33 CST 2020
     */
    public void setRoomStatus(Byte roomStatus) {
        this.roomStatus = roomStatus;
    }
}