package com.hotel.entity;

import java.util.ArrayList;
import java.util.List;

public class StaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public StaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Integer value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Integer value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Integer value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Integer value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Integer> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Integer> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffAgeIsNull() {
            addCriterion("staff_age is null");
            return (Criteria) this;
        }

        public Criteria andStaffAgeIsNotNull() {
            addCriterion("staff_age is not null");
            return (Criteria) this;
        }

        public Criteria andStaffAgeEqualTo(Integer value) {
            addCriterion("staff_age =", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeNotEqualTo(Integer value) {
            addCriterion("staff_age <>", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeGreaterThan(Integer value) {
            addCriterion("staff_age >", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_age >=", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeLessThan(Integer value) {
            addCriterion("staff_age <", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeLessThanOrEqualTo(Integer value) {
            addCriterion("staff_age <=", value, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeIn(List<Integer> values) {
            addCriterion("staff_age in", values, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeNotIn(List<Integer> values) {
            addCriterion("staff_age not in", values, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeBetween(Integer value1, Integer value2) {
            addCriterion("staff_age between", value1, value2, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_age not between", value1, value2, "staffAge");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIsNull() {
            addCriterion("staff_type is null");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIsNotNull() {
            addCriterion("staff_type is not null");
            return (Criteria) this;
        }

        public Criteria andStaffTypeEqualTo(String value) {
            addCriterion("staff_type =", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeNotEqualTo(String value) {
            addCriterion("staff_type <>", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeGreaterThan(String value) {
            addCriterion("staff_type >", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeGreaterThanOrEqualTo(String value) {
            addCriterion("staff_type >=", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeLessThan(String value) {
            addCriterion("staff_type <", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeLessThanOrEqualTo(String value) {
            addCriterion("staff_type <=", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeLike(String value) {
            addCriterion("staff_type like", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeNotLike(String value) {
            addCriterion("staff_type not like", value, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeIn(List<String> values) {
            addCriterion("staff_type in", values, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeNotIn(List<String> values) {
            addCriterion("staff_type not in", values, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeBetween(String value1, String value2) {
            addCriterion("staff_type between", value1, value2, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTypeNotBetween(String value1, String value2) {
            addCriterion("staff_type not between", value1, value2, "staffType");
            return (Criteria) this;
        }

        public Criteria andStaffTeleIsNull() {
            addCriterion("staff_tele is null");
            return (Criteria) this;
        }

        public Criteria andStaffTeleIsNotNull() {
            addCriterion("staff_tele is not null");
            return (Criteria) this;
        }

        public Criteria andStaffTeleEqualTo(Integer value) {
            addCriterion("staff_tele =", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleNotEqualTo(Integer value) {
            addCriterion("staff_tele <>", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleGreaterThan(Integer value) {
            addCriterion("staff_tele >", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_tele >=", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleLessThan(Integer value) {
            addCriterion("staff_tele <", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleLessThanOrEqualTo(Integer value) {
            addCriterion("staff_tele <=", value, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleIn(List<Integer> values) {
            addCriterion("staff_tele in", values, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleNotIn(List<Integer> values) {
            addCriterion("staff_tele not in", values, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleBetween(Integer value1, Integer value2) {
            addCriterion("staff_tele between", value1, value2, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffTeleNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_tele not between", value1, value2, "staffTele");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberIsNull() {
            addCriterion("staff_cardnumber is null");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberIsNotNull() {
            addCriterion("staff_cardnumber is not null");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberEqualTo(String value) {
            addCriterion("staff_cardnumber =", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberNotEqualTo(String value) {
            addCriterion("staff_cardnumber <>", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberGreaterThan(String value) {
            addCriterion("staff_cardnumber >", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberGreaterThanOrEqualTo(String value) {
            addCriterion("staff_cardnumber >=", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberLessThan(String value) {
            addCriterion("staff_cardnumber <", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberLessThanOrEqualTo(String value) {
            addCriterion("staff_cardnumber <=", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberLike(String value) {
            addCriterion("staff_cardnumber like", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberNotLike(String value) {
            addCriterion("staff_cardnumber not like", value, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberIn(List<String> values) {
            addCriterion("staff_cardnumber in", values, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberNotIn(List<String> values) {
            addCriterion("staff_cardnumber not in", values, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberBetween(String value1, String value2) {
            addCriterion("staff_cardnumber between", value1, value2, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffCardnumberNotBetween(String value1, String value2) {
            addCriterion("staff_cardnumber not between", value1, value2, "staffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStaffAdressIsNull() {
            addCriterion("staff_adress is null");
            return (Criteria) this;
        }

        public Criteria andStaffAdressIsNotNull() {
            addCriterion("staff_adress is not null");
            return (Criteria) this;
        }

        public Criteria andStaffAdressEqualTo(String value) {
            addCriterion("staff_adress =", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressNotEqualTo(String value) {
            addCriterion("staff_adress <>", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressGreaterThan(String value) {
            addCriterion("staff_adress >", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressGreaterThanOrEqualTo(String value) {
            addCriterion("staff_adress >=", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressLessThan(String value) {
            addCriterion("staff_adress <", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressLessThanOrEqualTo(String value) {
            addCriterion("staff_adress <=", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressLike(String value) {
            addCriterion("staff_adress like", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressNotLike(String value) {
            addCriterion("staff_adress not like", value, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressIn(List<String> values) {
            addCriterion("staff_adress in", values, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressNotIn(List<String> values) {
            addCriterion("staff_adress not in", values, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressBetween(String value1, String value2) {
            addCriterion("staff_adress between", value1, value2, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffAdressNotBetween(String value1, String value2) {
            addCriterion("staff_adress not between", value1, value2, "staffAdress");
            return (Criteria) this;
        }

        public Criteria andStaffStatusIsNull() {
            addCriterion("staff_status is null");
            return (Criteria) this;
        }

        public Criteria andStaffStatusIsNotNull() {
            addCriterion("staff_status is not null");
            return (Criteria) this;
        }

        public Criteria andStaffStatusEqualTo(Byte value) {
            addCriterion("staff_status =", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusNotEqualTo(Byte value) {
            addCriterion("staff_status <>", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusGreaterThan(Byte value) {
            addCriterion("staff_status >", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("staff_status >=", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusLessThan(Byte value) {
            addCriterion("staff_status <", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusLessThanOrEqualTo(Byte value) {
            addCriterion("staff_status <=", value, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusIn(List<Byte> values) {
            addCriterion("staff_status in", values, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusNotIn(List<Byte> values) {
            addCriterion("staff_status not in", values, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusBetween(Byte value1, Byte value2) {
            addCriterion("staff_status between", value1, value2, "staffStatus");
            return (Criteria) this;
        }

        public Criteria andStaffStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("staff_status not between", value1, value2, "staffStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_staff
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 08 17:23:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_staff
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}