package com.hotel.entity;

import java.util.ArrayList;
import java.util.List;

public class StuffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public StuffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuffIdIsNull() {
            addCriterion("stuff_id is null");
            return (Criteria) this;
        }

        public Criteria andStuffIdIsNotNull() {
            addCriterion("stuff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuffIdEqualTo(Integer value) {
            addCriterion("stuff_id =", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdNotEqualTo(Integer value) {
            addCriterion("stuff_id <>", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdGreaterThan(Integer value) {
            addCriterion("stuff_id >", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stuff_id >=", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdLessThan(Integer value) {
            addCriterion("stuff_id <", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdLessThanOrEqualTo(Integer value) {
            addCriterion("stuff_id <=", value, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdIn(List<Integer> values) {
            addCriterion("stuff_id in", values, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdNotIn(List<Integer> values) {
            addCriterion("stuff_id not in", values, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdBetween(Integer value1, Integer value2) {
            addCriterion("stuff_id between", value1, value2, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stuff_id not between", value1, value2, "stuffId");
            return (Criteria) this;
        }

        public Criteria andStuffNameIsNull() {
            addCriterion("stuff_name is null");
            return (Criteria) this;
        }

        public Criteria andStuffNameIsNotNull() {
            addCriterion("stuff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStuffNameEqualTo(String value) {
            addCriterion("stuff_name =", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameNotEqualTo(String value) {
            addCriterion("stuff_name <>", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameGreaterThan(String value) {
            addCriterion("stuff_name >", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameGreaterThanOrEqualTo(String value) {
            addCriterion("stuff_name >=", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameLessThan(String value) {
            addCriterion("stuff_name <", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameLessThanOrEqualTo(String value) {
            addCriterion("stuff_name <=", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameLike(String value) {
            addCriterion("stuff_name like", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameNotLike(String value) {
            addCriterion("stuff_name not like", value, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameIn(List<String> values) {
            addCriterion("stuff_name in", values, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameNotIn(List<String> values) {
            addCriterion("stuff_name not in", values, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameBetween(String value1, String value2) {
            addCriterion("stuff_name between", value1, value2, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffNameNotBetween(String value1, String value2) {
            addCriterion("stuff_name not between", value1, value2, "stuffName");
            return (Criteria) this;
        }

        public Criteria andStuffAgeIsNull() {
            addCriterion("stuff_age is null");
            return (Criteria) this;
        }

        public Criteria andStuffAgeIsNotNull() {
            addCriterion("stuff_age is not null");
            return (Criteria) this;
        }

        public Criteria andStuffAgeEqualTo(Integer value) {
            addCriterion("stuff_age =", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeNotEqualTo(Integer value) {
            addCriterion("stuff_age <>", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeGreaterThan(Integer value) {
            addCriterion("stuff_age >", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("stuff_age >=", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeLessThan(Integer value) {
            addCriterion("stuff_age <", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeLessThanOrEqualTo(Integer value) {
            addCriterion("stuff_age <=", value, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeIn(List<Integer> values) {
            addCriterion("stuff_age in", values, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeNotIn(List<Integer> values) {
            addCriterion("stuff_age not in", values, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeBetween(Integer value1, Integer value2) {
            addCriterion("stuff_age between", value1, value2, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("stuff_age not between", value1, value2, "stuffAge");
            return (Criteria) this;
        }

        public Criteria andStuffTypeIsNull() {
            addCriterion("stuff_type is null");
            return (Criteria) this;
        }

        public Criteria andStuffTypeIsNotNull() {
            addCriterion("stuff_type is not null");
            return (Criteria) this;
        }

        public Criteria andStuffTypeEqualTo(String value) {
            addCriterion("stuff_type =", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeNotEqualTo(String value) {
            addCriterion("stuff_type <>", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeGreaterThan(String value) {
            addCriterion("stuff_type >", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeGreaterThanOrEqualTo(String value) {
            addCriterion("stuff_type >=", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeLessThan(String value) {
            addCriterion("stuff_type <", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeLessThanOrEqualTo(String value) {
            addCriterion("stuff_type <=", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeLike(String value) {
            addCriterion("stuff_type like", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeNotLike(String value) {
            addCriterion("stuff_type not like", value, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeIn(List<String> values) {
            addCriterion("stuff_type in", values, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeNotIn(List<String> values) {
            addCriterion("stuff_type not in", values, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeBetween(String value1, String value2) {
            addCriterion("stuff_type between", value1, value2, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTypeNotBetween(String value1, String value2) {
            addCriterion("stuff_type not between", value1, value2, "stuffType");
            return (Criteria) this;
        }

        public Criteria andStuffTeleIsNull() {
            addCriterion("stuff_tele is null");
            return (Criteria) this;
        }

        public Criteria andStuffTeleIsNotNull() {
            addCriterion("stuff_tele is not null");
            return (Criteria) this;
        }

        public Criteria andStuffTeleEqualTo(String value) {
            addCriterion("stuff_tele =", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleNotEqualTo(String value) {
            addCriterion("stuff_tele <>", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleGreaterThan(String value) {
            addCriterion("stuff_tele >", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleGreaterThanOrEqualTo(String value) {
            addCriterion("stuff_tele >=", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleLessThan(String value) {
            addCriterion("stuff_tele <", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleLessThanOrEqualTo(String value) {
            addCriterion("stuff_tele <=", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleLike(String value) {
            addCriterion("stuff_tele like", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleNotLike(String value) {
            addCriterion("stuff_tele not like", value, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleIn(List<String> values) {
            addCriterion("stuff_tele in", values, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleNotIn(List<String> values) {
            addCriterion("stuff_tele not in", values, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleBetween(String value1, String value2) {
            addCriterion("stuff_tele between", value1, value2, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffTeleNotBetween(String value1, String value2) {
            addCriterion("stuff_tele not between", value1, value2, "stuffTele");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberIsNull() {
            addCriterion("stuff_cardnumber is null");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberIsNotNull() {
            addCriterion("stuff_cardnumber is not null");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberEqualTo(String value) {
            addCriterion("stuff_cardnumber =", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberNotEqualTo(String value) {
            addCriterion("stuff_cardnumber <>", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberGreaterThan(String value) {
            addCriterion("stuff_cardnumber >", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberGreaterThanOrEqualTo(String value) {
            addCriterion("stuff_cardnumber >=", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberLessThan(String value) {
            addCriterion("stuff_cardnumber <", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberLessThanOrEqualTo(String value) {
            addCriterion("stuff_cardnumber <=", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberLike(String value) {
            addCriterion("stuff_cardnumber like", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberNotLike(String value) {
            addCriterion("stuff_cardnumber not like", value, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberIn(List<String> values) {
            addCriterion("stuff_cardnumber in", values, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberNotIn(List<String> values) {
            addCriterion("stuff_cardnumber not in", values, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberBetween(String value1, String value2) {
            addCriterion("stuff_cardnumber between", value1, value2, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffCardnumberNotBetween(String value1, String value2) {
            addCriterion("stuff_cardnumber not between", value1, value2, "stuffCardnumber");
            return (Criteria) this;
        }

        public Criteria andStuffAdressIsNull() {
            addCriterion("stuff_adress is null");
            return (Criteria) this;
        }

        public Criteria andStuffAdressIsNotNull() {
            addCriterion("stuff_adress is not null");
            return (Criteria) this;
        }

        public Criteria andStuffAdressEqualTo(String value) {
            addCriterion("stuff_adress =", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressNotEqualTo(String value) {
            addCriterion("stuff_adress <>", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressGreaterThan(String value) {
            addCriterion("stuff_adress >", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressGreaterThanOrEqualTo(String value) {
            addCriterion("stuff_adress >=", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressLessThan(String value) {
            addCriterion("stuff_adress <", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressLessThanOrEqualTo(String value) {
            addCriterion("stuff_adress <=", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressLike(String value) {
            addCriterion("stuff_adress like", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressNotLike(String value) {
            addCriterion("stuff_adress not like", value, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressIn(List<String> values) {
            addCriterion("stuff_adress in", values, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressNotIn(List<String> values) {
            addCriterion("stuff_adress not in", values, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressBetween(String value1, String value2) {
            addCriterion("stuff_adress between", value1, value2, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffAdressNotBetween(String value1, String value2) {
            addCriterion("stuff_adress not between", value1, value2, "stuffAdress");
            return (Criteria) this;
        }

        public Criteria andStuffStatusIsNull() {
            addCriterion("stuff_status is null");
            return (Criteria) this;
        }

        public Criteria andStuffStatusIsNotNull() {
            addCriterion("stuff_status is not null");
            return (Criteria) this;
        }

        public Criteria andStuffStatusEqualTo(Byte value) {
            addCriterion("stuff_status =", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusNotEqualTo(Byte value) {
            addCriterion("stuff_status <>", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusGreaterThan(Byte value) {
            addCriterion("stuff_status >", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("stuff_status >=", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusLessThan(Byte value) {
            addCriterion("stuff_status <", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusLessThanOrEqualTo(Byte value) {
            addCriterion("stuff_status <=", value, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusIn(List<Byte> values) {
            addCriterion("stuff_status in", values, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusNotIn(List<Byte> values) {
            addCriterion("stuff_status not in", values, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusBetween(Byte value1, Byte value2) {
            addCriterion("stuff_status between", value1, value2, "stuffStatus");
            return (Criteria) this;
        }

        public Criteria andStuffStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("stuff_status not between", value1, value2, "stuffStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_stuff
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 10 08:56:31 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_stuff
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}