package com.hotel.entity;

public class Stuff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer stuffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String stuffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer stuffAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String stuffType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Integer stuffTele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String stuffCardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private String stuffAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_stuff.stuff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    private Byte stuffStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_id
     *
     * @return the value of tab_stuff.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStuffId() {
        return stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_id
     *
     * @param stuffId the value for tab_stuff.stuff_id
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffId(Integer stuffId) {
        this.stuffId = stuffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_name
     *
     * @return the value of tab_stuff.stuff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStuffName() {
        return stuffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_name
     *
     * @param stuffName the value for tab_stuff.stuff_name
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffName(String stuffName) {
        this.stuffName = stuffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_age
     *
     * @return the value of tab_stuff.stuff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStuffAge() {
        return stuffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_age
     *
     * @param stuffAge the value for tab_stuff.stuff_age
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffAge(Integer stuffAge) {
        this.stuffAge = stuffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_type
     *
     * @return the value of tab_stuff.stuff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStuffType() {
        return stuffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_type
     *
     * @param stuffType the value for tab_stuff.stuff_type
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffType(String stuffType) {
        this.stuffType = stuffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_tele
     *
     * @return the value of tab_stuff.stuff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Integer getStuffTele() {
        return stuffTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_tele
     *
     * @param stuffTele the value for tab_stuff.stuff_tele
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffTele(Integer stuffTele) {
        this.stuffTele = stuffTele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_cardnumber
     *
     * @return the value of tab_stuff.stuff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStuffCardnumber() {
        return stuffCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_cardnumber
     *
     * @param stuffCardnumber the value for tab_stuff.stuff_cardnumber
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffCardnumber(String stuffCardnumber) {
        this.stuffCardnumber = stuffCardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_adress
     *
     * @return the value of tab_stuff.stuff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public String getStuffAdress() {
        return stuffAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_adress
     *
     * @param stuffAdress the value for tab_stuff.stuff_adress
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffAdress(String stuffAdress) {
        this.stuffAdress = stuffAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_stuff.stuff_status
     *
     * @return the value of tab_stuff.stuff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public Byte getStuffStatus() {
        return stuffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_stuff.stuff_status
     *
     * @param stuffStatus the value for tab_stuff.stuff_status
     *
     * @mbg.generated Wed Jul 08 17:23:00 CST 2020
     */
    public void setStuffStatus(Byte stuffStatus) {
        this.stuffStatus = stuffStatus;
    }
}