package com.hotel.entity;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_desc
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private String typeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_price
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Double typePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.aval_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Integer avalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Integer typeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_type.type_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    private Byte typeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_id
     *
     * @return the value of tab_type.type_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_id
     *
     * @param typeId the value for tab_type.type_id
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_name
     *
     * @return the value of tab_type.type_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_name
     *
     * @param typeName the value for tab_type.type_name
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_desc
     *
     * @return the value of tab_type.type_desc
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_desc
     *
     * @param typeDesc the value for tab_type.type_desc
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_price
     *
     * @return the value of tab_type.type_price
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Double getTypePrice() {
        return typePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_price
     *
     * @param typePrice the value for tab_type.type_price
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypePrice(Double typePrice) {
        this.typePrice = typePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.aval_number
     *
     * @return the value of tab_type.aval_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Integer getAvalNumber() {
        return avalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.aval_number
     *
     * @param avalNumber the value for tab_type.aval_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setAvalNumber(Integer avalNumber) {
        this.avalNumber = avalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_number
     *
     * @return the value of tab_type.type_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Integer getTypeNumber() {
        return typeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_number
     *
     * @param typeNumber the value for tab_type.type_number
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypeNumber(Integer typeNumber) {
        this.typeNumber = typeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_type.type_status
     *
     * @return the value of tab_type.type_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public Byte getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_type.type_status
     *
     * @param typeStatus the value for tab_type.type_status
     *
     * @mbg.generated Fri Jul 10 08:56:31 CST 2020
     */
    public void setTypeStatus(Byte typeStatus) {
        this.typeStatus = typeStatus;
    }
}